project_id = "yrhdcigbbahylzfzbsnk"

[functions.mp-webhook]
verify_jwt = false

[functions.wallet-webhook]
verify_jwt = false

[functions.mp-refund]
verify_jwt = false

[functions.mp-tokenize-and-pay]
verify_jwt = false